[build]
  base = "."
  command = "bun install && bunx turbo build --filter=opencut"
  publish = "apps/web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://appcut.app/*"
  to = "https://opencut.app/:splat"
  status = 301
  force = true 